### ISSUE TITLE
Gamepad shuts off after a few seconds

### ISSUE THREAD

**Issue by jnaskali** [irungentoo/Xiaomi_gamepad#22]
I was able to install the service, and play a game successfully for a little while, but the controller(s) shut down after about 10 seconds of use. The console shows no extra information.

I can replicate the problem every time. Is it possible for me to send you some logs?

**Comment by irungentoo** [comment]
See: https://github.com/irungentoo/Xiaomi_gamepad/issues/11

**Comment by jnaskali** [comment]
I was highly sceptical about this, as it happened with two separate gamepads, but after buying new batteries and trying out the game, everything functions perfectly :) Thank you for the patient answer and your great work!

My girfriend said to write she loves you ;)
