### ISSUE TITLE
MI Button not Working

### ISSUE THREAD

**Issue by eiclu** [irungentoo/Xiaomi_gamepad#3]
I've installed the software yesterday and everything is working perfectly fine, except for the MI Button, which doesn't get registered in Windows

**Comment by irungentoo** [comment]
That button is a bit special, the controller only sends that it was pressed when you release it.

**Comment by eiclu** [comment]
Yeah, I understand that considering the button is used to turn off the device, but it doesn't get registered at all for me

**Comment by eiclu** [comment]
Is it possible to include the button in the software?

**Comment by irungentoo** [comment]
The button should be mapped to the middle button on the xbox controller, do games actually use it for something?

I'll look into it if I make an updated release of this software.

**Comment by eiclu** [comment]
In Steam big picture the Software uses the default config for a xbox Controller where the middle button is used to open the steam Overlay from within a game. This doesn't work for me. 
Also in the Windows Controller Settings this button isn't mapped

**Comment by irungentoo** [comment]
Fixed in latest release.

**Comment by tjaderxyz** [comment]
The Mi button is not working for me with the latest release. Is there anything I can do to help debug this?
