### ISSUE TITLE
 Delay with a second Xiaomi gamepad

### ISSUE THREAD

**Issue by Nioxder** [irungentoo/Xiaomi_gamepad#32]
Hello, I'm trying to play with two Xiaomi gamepads on the same pc, they connect well, my.exe detects them well in exclusive mode, but when I start a game (for example cars) the 1 command works ok, but the second gamepad has A delay in all the buttons, sometimes more time of delay and sometimes less.
I am doing something wrong??

P.D: Thanks for this incredible project

**Comment by irungentoo** [comment]
I only have access to one controller so it's hard for me to test this.

**Comment by Nioxder** [comment]
After testing many and several options the only way I have solved the problem has been buying a new bluetooth adapter, that if it cost me € 2, although the internal adapter of the pc is much better I do not know why it does not work correctly And with cheap Aliexpress adapter 0 problems. Go play local co-op !!!! Again many thanks for the project!
