### ISSUE TITLE
Not Working on Windows 10 14352

### ISSUE THREAD

**Issue by luminousmazim** [irungentoo/Xiaomi_gamepad#4]
It's weird. I decided to upgrade windows 10 insider build because it has a lot a new feature. But my xiaomi gamepad start not working on this build. I don't know, already install and uninstalled ScPdriver and mi.exe recognized my xiaomi gamepad. But in game it's not working. In device and printer control panel, has a xbox controller and xiaomi gamepad but when I did controller setting the only device work is xiaomi, and xbox doesn't respon any button I press. 

I think its something about bypassing controller I don't know. Can you help me?

**Comment by luminousmazim** [comment]
x360ce recognize 2 controller too, first xbox 360 controller and xiaomi gamepad. Xiaomi gamepad work, but xbox 360 controller didn't respon at all when I trying to configure at it. 

I believe it's something about application didn't by pass xiaomi controller

**Comment by irungentoo** [comment]
Close all the applications that might be using the controller then unpair it and pair it again. Then run mi.exe

If it works, you should only see an xbox controller in your settings, the xiaomi entry should disappear when you run mi.exe

**Comment by luminousmazim** [comment]
Tried, but xiaomi gamepad still detected in control panel

**Comment by irungentoo** [comment]
If mi.exe stays open and doesn't print any errors or exceptions it means it's a windows issue.

I would downgrade to a stable version of windows.

**Comment by irungentoo** [comment]
Fixed in latest release.
