### ISSUE TITLE
no executable files for the windows form version? 

### ISSUE THREAD

**Issue by fugogugo** [irungentoo/Xiaomi_gamepad#42]
Helloo

the latest version doesn't give any instruction of how to install them.
do we need to download and install visual studio to compile them manually?
Seriously though, I prefer the command prompt version.

**Comment by ThmsD** [comment]
There is a README.txt in the release package.

**Comment by fugogugo** [comment]
where is this release package?

Ahh nevermind 
https://github.com/irungentoo/Xiaomi_gamepad/releases

sorry I'm not really familiar with github yet. .__.

thank you very much!
