### ISSUE TITLE
Accelerometer - Dolphin Emulator

### ISSUE THREAD

**Issue by diegoweb** [irungentoo/Xiaomi_gamepad#44]
If I`m right, our gamepads do have built-in accelerometer.
Is it possible to setup this function with Dolphin Emulator?

Or does this script still doesn`t have accelerometer developed?

Thanks! (I didn`t know where to post, I`m not used to github).

**Comment by sorryusernameisalreadytaken** [comment]
In the text is written:

> 1 dpad
> 2
>  joysticks
> 2 triggers
> 2 rumble motors with variable speeds
> 1 3 axis accelerometer

Do you 100% know that the dolphin emulator support accelerometer from third-p. devices?

**Comment by diegoweb** [comment]
I am not sure if it uses accelerometer, it is called TILT in Dolphin Emulator.

If you search for "Dolphin Emulator Tilt" there will be a lot of guides of how to emulate them with a lot of devices. I wonder if it uses accelerometer for that.

**Comment by OneCrazyRussian** [comment]
Doplhin accelerometer support was made for Wiimotes (as they are fully supported by it) and as far as I know other than them you can only map it to certain controller buttons (sticks should 100% work)

On the other hand if this driver has the gyro exposed (as 2d sliders, like Sixaxis unofficial drivers did, for example) then you can map the tilt to the corresponding sliders, as sixaxis configs did
