### ISSUE TITLE
Problem in Liquidsky

### ISSUE THREAD

**Issue by mahdi-ln** [irungentoo/Xiaomi_gamepad#60]
The player view goes down constantly in Liquidsky. If original gamepad be disabled somehow  (and only virtual one be the only enabled one) this problem will be solved. I wasn't able to manually do that.

**Comment by mahdi-ln** [comment]
I think it solved by installing Tocaedit & .net framwork 3.5

**Comment by mahdi-ln** [comment]
problem is this: https://photos.app.goo.gl/l7esJecSXErOMCUz1
and obviously this: https://photos.app.goo.gl/SYUGvG0wXfHK3j583

**Comment by Mahdi-ME** [comment]
This is solution: https://github.com/irungentoo/Xiaomi_gamepad/issues/12#issuecomment-240420202
