### ISSUE TITLE
Same problem with new Windows 10

### ISSUE THREAD

**Issue by luminousmazim** [irungentoo/Xiaomi_gamepad#7]
Hey I have same problem with the new build windows 10 (Redstone Build). With the new release mi.exe, now app showing some error. It said "Couldn't open gamepad in exclusive mode, ..... attempting to open in shared mode. 

Like I said before, I already close anything that may use my controller and I check with Process Explorer, to make sure no app using my controller. And same error still persist. Can you fix it? I know you maybe suggest me using old windows 10, but Redstone build will available to everyone in July and I think everyone who use windows 10 will update to this build because it more stable (Microsoft Edge, many more) and more polished. So, yeah, if you can fix this problem that will be great. Anyway thanks for this app!

**Comment by luminousmazim** [comment]
Its weird I did something to make this work. I disable HID-Compliant game Controller in device manager, at open mi.exe it show 0 Controller and close mi.exe and enable HID-Compliant game Controller again, open mi.exe then Poof it work. Weird...

**Comment by irungentoo** [comment]
> Couldn't open gamepad in exclusive mode

That's not a fatal error, if it prints that 1 controller was connected then it works.

If you want it to open in exclusive mode close everything including windows stuff that could be opening the gamepad. For example I know that mumble is one program that opens it for some reason.

**Comment by luminousmazim** [comment]
But when not in exclusive mode, all gamepad working at the same time. That's make 1 button have double function in game. I think the problem with the new game bar (Xbox gamebar) in windows 10. Hope disable it will solve the problem.

**Comment by tu-nv** [comment]
The exclusive problem happened once in the past. Then it was fixed at the version 1511. Do not know why it happens once again.

**Comment by irungentoo** [comment]
Fixed in latest release.
