### ISSUE TITLE
d-pad up is pressed by ghost sporadically

### ISSUE THREAD

**Issue by panhans** [irungentoo/Xiaomi_gamepad#8]
I palyed yesterday spintires over internet with my friend. (everyone on another pc) and every 10 minutes (circa) the d-pad up-button was triggerd for some reason on both machines.

**Comment by luminousmazim** [comment]
Same problem with me. It's really annoying when playing gta v. I thought it just me..

**Comment by irungentoo** [comment]
Fixed in latest release.
