### ISSUE TITLE
Wrong X rotation Compared Original XBOX360 Controller

### ISSUE THREAD

**Issue by indraAsLesmana** [irungentoo/Xiaomi_gamepad#9]
![2016-03-31_164304](https://cloud.githubusercontent.com/assets/12571554/16417622/2c96c7a4-3d79-11e6-94e6-7908a21e62a0.png)

i try to play metro lastlight redux and metro 2033 Redux, if i moved with left analog to left, right, and down,and back to the center analog.. left analog still moved little bit with last direction. than i look to properties controller on windows i thinks X Rotation isn't right. if i compare with original x360 controller. you can see the differences with this picture.. thanks

and this is,Xbox One properties : http://www.hanselman.com/blog/content/binary/xboxonecontrolleronpc.gif

Game i tryed:

Third person:
Mad Max 2015 (Work great)
Specof the line (Work great)

Race:
Motogp 2015 (Work great)
grid 2 (Work great)

FPS:
Metro lastlight & metro 2033 Redux Edition (Problem left analog still moved little bit to last direction)
Metro 2033 'pirate' (Problem left analog still moved little bit to last direction)

**Comment by irungentoo** [comment]
From your pictures, your original xbox controller looks like it's decalibrated. The xiaomi gamepad picture is what it's supposed to look like when your left stick is in the center.

**Comment by indraAsLesmana** [comment]
another FPS game "FAR CRY 3" controller works great.. i think the problem come only with all Metro game. sadly its my favorite game. thanks for this project the vibration reallyyyy great.. if you have metro game, i suggest you to try with this project.. thanks irugentoo
